// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplySpicetifyTheme(arg1:string):Promise<boolean>;

export function CheckInstallation():Promise<main.InstallStatus>;

export function DeleteSpicetifyApp(arg1:string):Promise<boolean>;

export function DeleteSpicetifyExtension(arg1:string):Promise<boolean>;

export function DeleteSpicetifyTheme(arg1:string):Promise<boolean>;

export function GetAddonAssetPath(arg1:string):Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetSettings():Promise<main.AppSettings>;

export function GetSpicetifyApps():Promise<Array<main.AppInfo>>;

export function GetSpicetifyExtensions():Promise<Array<main.AddonInfo>>;

export function GetSpicetifyThemes():Promise<Array<main.ThemeInfo>>;

export function GetSpicetifyVersion():Promise<string>;

export function GetSpotifyVersion():Promise<string>;

export function GetThemeAssetPath(arg1:string):Promise<string>;

export function InstallMarketplaceApp(arg1:string,arg2:string,arg3:string,arg4:any,arg5:main.MarketplaceMeta):Promise<boolean>;

export function InstallMarketplaceExtension(arg1:string,arg2:string,arg3:main.MarketplaceMeta):Promise<boolean>;

export function InstallMarketplaceTheme(arg1:string,arg2:string,arg3:any,arg4:Array<string>,arg5:main.MarketplaceMeta):Promise<boolean>;

export function InstallSpicetifyBinary():Promise<void>;

export function OpenConfigFolder():Promise<boolean>;

export function OpenExternalLink(arg1:string):Promise<boolean>;

export function ReloadSpicetify():Promise<boolean>;

export function SetCloseToTray(arg1:boolean):Promise<void>;

export function SetColorScheme(arg1:string,arg2:string):Promise<boolean>;

export function SetRpcActivity(arg1:string):Promise<void>;

export function SetupSpicetifyAssets():Promise<void>;

export function StartInstall():Promise<void>;

export function StartRestore():Promise<void>;

export function ToggleDiscordRpc(arg1:boolean):Promise<void>;

export function ToggleSpicetifyApp(arg1:string,arg2:boolean):Promise<boolean>;

export function ToggleSpicetifyExtension(arg1:string,arg2:boolean):Promise<boolean>;

export function UpdateSettings(arg1:Record<string, any>):Promise<main.AppSettings>;

export function WindowClose():Promise<void>;

export function WindowMinimize():Promise<void>;
