// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplySpicetifyTheme(arg1) {
  return window['go']['main']['App']['ApplySpicetifyTheme'](arg1);
}

export function CheckInstallation() {
  return window['go']['main']['App']['CheckInstallation']();
}

export function DeleteSpicetifyApp(arg1) {
  return window['go']['main']['App']['DeleteSpicetifyApp'](arg1);
}

export function DeleteSpicetifyExtension(arg1) {
  return window['go']['main']['App']['DeleteSpicetifyExtension'](arg1);
}

export function DeleteSpicetifyTheme(arg1) {
  return window['go']['main']['App']['DeleteSpicetifyTheme'](arg1);
}

export function GetAddonAssetPath(arg1) {
  return window['go']['main']['App']['GetAddonAssetPath'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSpicetifyApps() {
  return window['go']['main']['App']['GetSpicetifyApps']();
}

export function GetSpicetifyExtensions() {
  return window['go']['main']['App']['GetSpicetifyExtensions']();
}

export function GetSpicetifyThemes() {
  return window['go']['main']['App']['GetSpicetifyThemes']();
}

export function GetSpicetifyVersion() {
  return window['go']['main']['App']['GetSpicetifyVersion']();
}

export function GetSpotifyVersion() {
  return window['go']['main']['App']['GetSpotifyVersion']();
}

export function GetThemeAssetPath(arg1) {
  return window['go']['main']['App']['GetThemeAssetPath'](arg1);
}

export function InstallMarketplaceApp(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['InstallMarketplaceApp'](arg1, arg2, arg3, arg4, arg5);
}

export function InstallMarketplaceExtension(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallMarketplaceExtension'](arg1, arg2, arg3);
}

export function InstallMarketplaceTheme(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['InstallMarketplaceTheme'](arg1, arg2, arg3, arg4, arg5);
}

export function InstallSpicetifyBinary() {
  return window['go']['main']['App']['InstallSpicetifyBinary']();
}

export function OpenConfigFolder() {
  return window['go']['main']['App']['OpenConfigFolder']();
}

export function OpenExternalLink(arg1) {
  return window['go']['main']['App']['OpenExternalLink'](arg1);
}

export function ReloadSpicetify() {
  return window['go']['main']['App']['ReloadSpicetify']();
}

export function SetCloseToTray(arg1) {
  return window['go']['main']['App']['SetCloseToTray'](arg1);
}

export function SetColorScheme(arg1, arg2) {
  return window['go']['main']['App']['SetColorScheme'](arg1, arg2);
}

export function SetRpcActivity(arg1) {
  return window['go']['main']['App']['SetRpcActivity'](arg1);
}

export function SetupSpicetifyAssets() {
  return window['go']['main']['App']['SetupSpicetifyAssets']();
}

export function StartInstall() {
  return window['go']['main']['App']['StartInstall']();
}

export function StartRestore() {
  return window['go']['main']['App']['StartRestore']();
}

export function ToggleDiscordRpc(arg1) {
  return window['go']['main']['App']['ToggleDiscordRpc'](arg1);
}

export function ToggleSpicetifyApp(arg1, arg2) {
  return window['go']['main']['App']['ToggleSpicetifyApp'](arg1, arg2);
}

export function ToggleSpicetifyExtension(arg1, arg2) {
  return window['go']['main']['App']['ToggleSpicetifyExtension'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMinimize() {
  return window['go']['main']['App']['WindowMinimize']();
}
